### PR TITLE
rdt ssh: Default to /bin/bash if it exists

### LINKED ISSUE #69: Tab completion during `rdt ssh` has unexpected behaviour
* `rdt` version: 0.0.8
* Operating system and architecture: OSX 10.11.5

If you drop into the container using `rdt ssh` and try use TAB completion in the terminal, the terminal seems to handle the TAB as an actual TAB and just move the cursor rightwards along the terminal.

I would expect it to complete the command or path suggestions as regular bash does.

### PR DESCRIPTION
**Pull request by lekkas**
Closes #69 #64

### CODE REVIEW

File: lib/actions/ssh.coffee [hunk 1]
```diff
@@ -118,7 +118,8 @@ module.exports =
 				 root@#{options.deviceIp}"
 
 			if not options.host
-			 command += " docker exec -ti #{container} /bin/sh"
+				shellCmd = '/bin/sh -c $"\'if [ -e /bin/bash ]; then exec /bin/bash; else exec /bin/sh; fi\'"'
```
Comment (Page-) [inline lib/actions/ssh.coffee]: Can we use `'''`/`"""` so that we can avoid having to add coffee-script escaping to the bash string, that'll make it a bit easier to read

Comment (lekkas) [inline lib/actions/ssh.coffee]: @Page- fixed - this particular bash snippet still is kind of hard to read though :/

**Comment by lekkas** [comment]
@Page- reping for approval (or not)
